# Generated by Django 3.2.4 on 2024-11-04 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zomatoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="delivery_address",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(200)],
            ),
        ),
    ]
