# Generated by Django 3.2.4 on 2024-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zomatoapp", "0002_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooditem",
            old_name="price",
            new_name="unit_price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="food_id",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="food_item",
        ),
        migrations.AddField(
            model_name="fooditem",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
