# Generated by Django 3.2.4 on 2024-11-05 14:31

import ZomatoProj.zomatoapp.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0002_alter_user_delivery_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ZomatoProj.zomatoapp.models.user.CustomUserManager()),
            ],
        ),
    ]
