# Generated by Django 3.2.4 on 2024-11-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("zomatoapp", "0004_category_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="zomatoapp.menu",
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_items",
                to="zomatoapp.category",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="restaurant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu",
                to="zomatoapp.restaurant",
            ),
        ),
    ]
